SalesSystem/Controllers/ResourceTypeController.cs
using Microsoft.AspNetCore.Mvc;
using static SalesSystem.Helper;

namespace SalesSystem.Controllers
{
    public class ResourceTypeController : Controller
        

    {
        private readonly ApplicationDbContext _context;
        private readonly IResourceTypeServices _resourceTypeServices;

        public ResourceTypeController(ApplicationDbContext context,IResourceTypeServices resourceTypeServices)
        {
           _context = context;
            _resourceTypeServices = resourceTypeServices;
        }

        
        public IActionResult Index()
        {
            var resourceTypes = _resourceTypeServices.GetAll();
            return View(resourceTypes);
        }
        [HttpGet]
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new CreateResourceTypeFormViewModel());
            else
            {
                var resorceTypeModel = _resourceTypeServices.GetById(id);
                if (resorceTypeModel == null)
                {
                    return NotFound();
                }
                CreateResourceTypeFormViewModel viewModel = new()
                {
                    Id = id,
                    Name = resorceTypeModel.Name,
                    Desc = resorceTypeModel.Desc,
                   

                };

                return View(viewModel);

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]


        public async Task<IActionResult> AddOrEdit(int id, CreateResourceTypeFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    await _resourceTypeServices.Add(model);
                }
                //Update
                else
                {
                    try
                    {
                        await _resourceTypeServices.Update(model);

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!resourcetypeModelExists(model.Id))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                }
                // return RedirectToAction("Index");
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.resourceTypes.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", model) });
        }


        private bool resourcetypeModelExists(int id)
        {
            return _context.resourceTypes.Any(e => e.Id == id);
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _resourceTypeServices.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }
    }
}

SalesSystem/Views/ResourceType/AddOrEdit.cshtml
@model CreateResourceTypeFormViewModel
@{
    Layout = null;
}
@{
    ViewData["Title"] = "اضافه مجموعة موردين";
}


<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Desc" class="control-label"></label>
                        <input asp-for="Desc" class="form-control" />
                        <span asp-validation-for="Desc" class="text-danger"></span>
                    </div>
                </div>
             </div>
            <div class="form-group">
                <div class="col-md-12 ">
                    <input type="submit" value="حفظ" class="btn btn-primary btn-block m-2" />
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts
{
   @*  <partial name="_ValidationScriptsPartial" />
  *@  
  
  @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/stock.js" asp-append-version="true"></script>
 
}

SalesSystem/Views/ResourceType/Index.cshtml
@model IEnumerable<ResourceType>

@{
    ViewData["Title"] = " سجل مجموعة الموردين";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/stock.js" asp-append-version="true"></script>

}

SalesSystem/Views/ResourceType/_ViewAll.cshtml
@model IEnumerable<ResourceType>

@{
    ViewData["Title"] = " سجل مجموعة الموردين";
}

<a class="btn btn-success text-white btn-lg" onclick="showInPopup('@Url.Action("AddOrEdit","ResourceType",null,Context.Request.Scheme)','اضافة مجموعة موردين')">

    <i class="bi bi-plus-circle-dotted"></i>
    اضافة مجموعة موردين
</a>

@if (!Model.Any())
{
    <div class="alert alert-warning mt-5">
        <h4 class="alert-heading">لا يوجد مجموعة موردين</h4>
        <p class="mb-0">لم يتم اضافة مجموعة موردين.</p>
    </div>
}
else
{
    <div class="mt-5">
        <table class="table table-hover" id="sampleTable">
            <thead>
                <tr>
                    <th scope="col">اسم المجموعة </th>
                    <th scope="col">وصف المجموعة  </th>

                   
                    <th scope="col">الاحداث  </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var resourcetype in Model)
                {
                    <tr>



                        <td>@resourcetype.Name</td>
                        <td>@resourcetype.Desc</td>


                        

                      <td>
                            <a onclick="showInPopup('@Url.Action("AddOrEdit","ResourceType",new {id=resourcetype.Id},Context.Request.Scheme)',' تعديل مجموعة الموردين')" class="btn btn-info rounded rounded-3 me-2">
                                <i class="bi bi-pencil-fill"></i>
                            </a>
                            <a href="javascript:;" class="btn btn-danger rounded rounded-3 js-delete" data-id="@resourcetype.Id">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </td>




                    </tr>
                }

            </tbody>
        </table>
    </div>
}